name: Build

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - '*'


jobs:
  ubuntu:
    name: ${{ matrix.ubuntu_image }}
    runs-on: ${{ matrix.ubuntu_image }}
    strategy:
      fail-fast: false
      matrix:
        ubuntu_image: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v2
      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y gperf
      - uses: actions/cache@v2
        id: cache
        with:
          path: ./install
          key: ${{ github.job }}-${{ hashFiles('./dependencies/**') }}
      - name: Configure and build dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
            cmake -DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE}/install -DCMAKE_INSTALL_PREFIX=install -Bdependencies/build -Sdependencies
            cmake --build dependencies/build
      - name: Configure and build project
        run: |
            cmake -DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE}/install -Bbuild -S.
            cmake --build build

  dockcross-android:
    name: ${{ matrix.name }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: android-arm
            arch: armeabi-v7a
          - name: android-arm64
            arch: arm64-v8a
    steps:
      - uses: actions/checkout@v2
      - name: Setup dockcross
        run: docker run --rm dockcross/${{ matrix.name }} > ./dockcross-${{ matrix.name }}; chmod +x ./dockcross-${{ matrix.name }}
      - uses: actions/cache@v2
        id: cache
        with:
          path: ./install
          key: ${{ github.job }}-${{ hashFiles('./dependencies/**') }}
      - name: Configure and build dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
            ./dockcross-${{ matrix.name }} cmake -DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE}/install -DCMAKE_INSTALL_PREFIX=install -Bdependencies/build -Sdependencies
            ./dockcross-${{ matrix.name }} cmake --build dependencies/build
      - name: Configure and build project
        run: |
            ./dockcross-${{ matrix.name }} cmake -DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE}/install -Bbuild -S.
            ./dockcross-${{ matrix.name }} cmake --build build
